import { Dimensions, StyleSheet } from 'react-native';
import type { ThemePalette } from '../context/ThemeContext';

const WINDOW = Dimensions.get('window');

export const appStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#ecfdf5' },
  header: { backgroundColor: '#fff', padding: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  title: { fontSize: 20, fontWeight: '700', color: '#065f46' },
  smallMuted: { color: '#6b7280', fontSize: 12 },
  content: { flex: 1, paddingHorizontal: 12, paddingTop: 8, paddingBottom: 12 },
  h2: { fontSize: 18, fontWeight: '700', color: '#065f46', marginTop: 8 },
  h3: { fontSize: 16, fontWeight: '700', color: '#065f46' },
  h4: { fontSize: 14, fontWeight: '700', color: '#111827' },
  p: { color: '#4b5563', marginTop: 6 },
  small: { fontSize: 12, color: '#6b7280' },
  centeredColumn: { alignItems: 'center', padding: 20 },
  btn: { paddingVertical: 10, paddingHorizontal: 12, borderRadius: 10, borderWidth: 1, borderColor: '#e5e7eb', backgroundColor: '#fff', alignItems: 'center' },
  btnPrimary: { backgroundColor: '#16a34a', borderColor: 'transparent' },
  btnText: { color: '#111827', fontWeight: '600' },
  btnTextPrimary: { color: '#fff' },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  card: { backgroundColor: '#fff', padding: 12, borderRadius: 12, marginVertical: 8, shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 6 },
  centeredCard: { alignItems: 'center', padding: 20, borderRadius: 12, marginVertical: 8, backgroundColor: '#f0fff4' },
  scheduleItem: { flexDirection: 'row', alignItems: 'center', padding: 8, backgroundColor: '#f8fafc', borderRadius: 10, marginVertical: 6 },
  iconButton: { padding: 6, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  iconButtonDanger: { padding: 6, borderRadius: 999, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(220,38,38,0.08)' },
  subTabRow: { flexDirection: 'row', marginVertical: 12 },
  subTabButton: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12, backgroundColor: '#fff' },
  subTabActive: { backgroundColor: '#16a34a' },
  subTabText: { color: '#374151' },
  subTabTextActive: { color: '#fff' },
  gardenBtn: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12, marginRight: 8 },
  gardenBtnActive: { backgroundColor: '#16a34a' },
  gardenBtnInactive: { backgroundColor: '#fff' },
  gardenBtnTextActive: { color: '#fff' },
  gardenBtnTextInactive: { color: '#374151' },
  tag: { backgroundColor: '#f1f5f9', paddingHorizontal: 8, paddingVertical: 6, borderRadius: 12 },
  gridContainer: { padding: 8, flexDirection: 'column' },
  gardenBed: { 
    padding: 12, 
    flexDirection: 'column', 
    backgroundColor: '#5d4e37',
    borderRadius: 16,
    borderWidth: 8,
    borderColor: '#8B7355',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
    marginVertical: 8,
  },
  gridRow: { flexDirection: 'row', marginBottom: 6 },
  cell: { width: 85, height: 85, borderRadius: 8, alignItems: 'center', justifyContent: 'center', marginRight: 6 },
  cellFilled: { backgroundColor: '#ecfdf5', borderWidth: 2, borderColor: '#34d399' },
  cellEmpty: { backgroundColor: '#fffbeb', borderWidth: 2, borderStyle: 'dashed', borderColor: '#f59e0b' },
  cellContent: { alignItems: 'center', justifyContent: 'center', position: 'relative', width: '100%', height: '100%' },
  cellRemove: { position: 'absolute', top: 4, right: 4, padding: 4, borderRadius: 999, backgroundColor: 'rgba(220,38,38,0.12)' },
  cellLabel: { fontSize: 12, fontWeight: '600', color: '#374151', marginTop: 4 },
  cellAdd: { color: '#6b7280', marginTop: 4 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', alignItems: 'center', justifyContent: 'center', padding: 16 },
  modalCard: { width: Math.min(WINDOW.width - 32, 720), maxWidth: WINDOW.width - 32, backgroundColor: '#fff', padding: 16, borderRadius: 16, maxHeight: WINDOW.height - 120 },
  modalCardLarge: { width: Math.min(WINDOW.width - 32, 920), maxWidth: WINDOW.width - 32, backgroundColor: '#fff', padding: 16, borderRadius: 16, maxHeight: WINDOW.height - 120 },
  input: { borderWidth: 1, borderColor: '#e5e7eb', padding: 12, borderRadius: 10, marginTop: 8, backgroundColor: '#fff' },
  plantCard: { flex: 1, margin: 8, backgroundColor: '#fff', padding: 12, borderRadius: 12, alignItems: 'center' },
  plantCardSmall: { flex: 1, margin: 8, backgroundColor: '#fff', padding: 12, borderRadius: 12, alignItems: 'center', width: 100 },
  tabBar: { backgroundColor: '#fff', borderTopWidth: 1, borderColor: '#e6e6e6', paddingVertical: 8, flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center' },
  tabBtn: { alignItems: 'center', padding: 8, flex: 1 },
  tabText: { fontSize: 11, color: '#6b7280', marginTop: 4 },
  tabTextActive: { fontSize: 11, color: '#16a34a', marginTop: 4 },
  tabCenterInline: { alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6 },
  tabCenterInner: { width: 56, height: 56, borderRadius: 999, backgroundColor: '#16a34a', alignItems: 'center', justifyContent: 'center', borderWidth: 3, borderColor: '#fff' },
  floatingTabWrap: { position: 'absolute', left: 0, right: 0, alignItems: 'center', pointerEvents: 'box-none' },
  floatingTabBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#fff', paddingVertical: 10, paddingHorizontal: 12, borderRadius: 999, width: Math.min(WINDOW.width - 48, 420), shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 10, elevation: 8 },
  tabBtnFloating: { alignItems: 'center', justifyContent: 'center', flex: 1, padding: 6 },
  tabCenterFloating: { alignItems: 'center', justifyContent: 'center', paddingHorizontal: 8 }
});

export type AppStyles = typeof appStyles;
export const windowMetrics = WINDOW;

export function makeThemedStyles(p: ThemePalette) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: p.background },
    card: { backgroundColor: p.surface, padding: 12, borderRadius: 12, marginVertical: 8, borderColor: p.border, borderWidth: StyleSheet.hairlineWidth },
    h2: { fontSize: 18, fontWeight: '700', color: p.primary, marginTop: 8 },
    h3: { fontSize: 16, fontWeight: '700', color: p.primary },
    h4: { fontSize: 14, fontWeight: '700', color: p.text },
    p: { color: p.text, marginTop: 6 },
    small: { fontSize: 12, color: p.textMuted },
    btn: { paddingVertical: 10, paddingHorizontal: 12, borderRadius: 10, borderWidth: 1, borderColor: p.border, backgroundColor: p.surface, alignItems: 'center' },
    btnPrimary: { backgroundColor: p.primary, borderColor: 'transparent' },
    btnText: { color: p.text, fontWeight: '600' },
    btnTextPrimary: { color: '#fff' },
    rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    input: { borderWidth: 1, borderColor: p.border, padding: 12, borderRadius: 10, marginTop: 8, backgroundColor: p.surface, color: p.text },
    tag: { backgroundColor: p.surfaceMuted, paddingHorizontal: 8, paddingVertical: 6, borderRadius: 12 },
  });
}
